name = "bold-lake-b876"
main = "worker.js"
compatibility_date = "2024-01-01"
account_id = "9b5fdcc25e7cca3e9f17d69b9582f56a"

# memail worker - auto-deploy v2

[vars]
DEPLOY_SECRET = "memail-deploy-2026"
